### ISSUE TITLE
Chapter 2, Section 2.5.3 Hyperparameter Tuning typo

### ISSUE THREAD

**Issue by benprew** [koalaverse/hands-on-machine-learning-with-r#10]
-__Typo__ Section 2.5.3 Hyperparameter Tuning

In this sentence:

> Figure 2.10 illustrates this point. Smaller k values (e.g., 2, 5, or 10) lead to high variance (but lower variance) and larger values (e.g., 150) lead to high bias (but lower variance).

Did you mean to say:

> Figure 2.10 illustrates this point. Smaller k values (e.g., 2, 5, or 10) lead to high variance (but lower ~~variance~~bias) and larger values (e.g., 150) lead to high bias (but lower variance).

Also, great book, I'm in a group that's going through ISLR, and your book is a nice supplement to that.

Thanks

**Comment by bgreenwell** [comment]
FIxed. Thanks @benprew!
