### ISSUE TITLE
Chapter 1 section 1.2 Unsupervised learning

### ISSUE THREAD

**Issue by asimumba** [koalaverse/hands-on-machine-learning-with-r#12]
Book version __2019-06-01__
>The goal of clustering is to segment observations into similar groups based on the observed variables; for example, to divide consumers into different homogeneous groups, a process known as market segmentation. In dimension reduction, we are often concerned with reducing the number of variables in a data set. For example, classical linear regression models break down in the presence of highly correlated features. Some dimension reduction techniques can be used reduce the feature set to a potentially smaller set of uncorrelated variables.

There is a missing "to" in the last sentence of the paragraph above. Highlighted in bold below.

 For example, classical linear regression models break down in the presence of highly correlated features. Some dimension reduction techniques can be used **to** reduce the feature set to a potentially smaller set of uncorrelated variables.

**Edit** 
Same section as above

 >Such a reduced feature set is often used as input to downstream supervised learning models (e.g., **principle component regression**).

The highlighted has to read as **principal component regression**

**Comment by bradleyboehmke** [comment]
Thanks @asimumba, we corrected these issues in the most recent version.
