### ISSUE TITLE
Is Potential Problem with code or my machine?

### ISSUE THREAD

**Issue by mccurcio** [koalaverse/hands-on-machine-learning-with-r#27]
I am working through sections of [HOML/autoencoders.html](https://bradleyboehmke.github.io/HOML/autoencoders.html) and found an error message pop up.

In section: 19.2.3 Visualizing the reconstruction, I found an error associated with the line:
```
# Predict reconstructed pixel values  
best_model_id <- grid_perf@model_ids[[1]]
```

after this line I get: 
```
Error: object 'grid_perf' not found
```

Up to this point, I have followed the code from the Autoencoder section, should I look at my setup or  is this a change in H2O.ai and code?
HTH

**Comment by bradleyboehmke** [comment]
Good catch @mccurcio , this is actually an error on the code side. If you replace that line with 

```r
best_model_id <- ae_grid@model_ids[[1]]
```

then it should work just fine. I will be updating the online version of the book with this correction shortly.

**Comment by bradleyboehmke** [comment]
The online version of the book has been updated. Thanks @mccurcio
