### ISSUE TITLE
Possibly wrong number in caption of Figure 7.7

### ISSUE THREAD

**Issue by lcreteig** [koalaverse/hands-on-machine-learning-with-r#28]
First off, thank you so much for creating this book and making it freely available! It has been a really great resource so far for me. 

I think there's a small inaccuracy in the caption of Figure 7.7:

> Figure 7.7: Cross-validated accuracy rate for the 30 different hyperparameter combinations in our grid search. The optimal model retains 45 terms and includes no interaction effects.

From looking at the graph and the output in the code chunk above Figure 7.7, I think "45 terms" should be "12 terms" (seems to be a remnant from Figure 7.4).

- [Link to subsection with figure](https://bradleyboehmke.github.io/HOML/mars.html#attrition-data-1) 
- Date on first page: 2020-01-30

**Comment by bradleyboehmke** [comment]
Nice catch @lcreteig. I've corrected the figure caption on the online version. Thanks!
