### ISSUE TITLE
chapter 5, suggestion: reasons to avoid linear regression

### ISSUE THREAD

**Issue by cunningjames** [koalaverse/hands-on-machine-learning-with-r#3]
Book version: 2019-05-25

Section 5.2: Consider mentioning other reasons that linear regression is unsuitable for classification, such as sensitivity to imbalances and outliers. The section might give the impression that it's not so terrible to use what we used to call the "linear probability model" in econometrics. (Bleah.)

**Comment by bradleyboehmke** [comment]
Added a sentence to the first paragraph in 5.2 that highlights these other reasons.
