### ISSUE TITLE
chapter 5, suggestion: consider avoiding discussion about log odds

### ISSUE THREAD

**Issue by cunningjames** [koalaverse/hands-on-machine-learning-with-r#5]
Book version: 2019-05-25

I tend to find discussion about log odds confusing and not easily interpretable, and in the chapter the interpretation is log odds isn't really used for anything. Unless you're going to be talking more generally about GLMs, consider just keeping the discussion in terms of good ol' probability.

**Comment by bgreenwell** [comment]
Log odds are pretty important and so I'd be hesitant to remove entirely, but I'll try and refine the discussion a bit. I also haven't got to the IML chapter, but feature effect plots for classification models are more useful on a logit-type scale so I plan to add some more discussion there as well.

**Comment by cunningjames** [comment]
That works. I’ll be interested to see how the effect plots are more useful in terms of log odds! #logitsareeviluseprobits

**Comment by bgreenwell** [comment]
Revised.
