### ISSUE TITLE
IF there was a small mistake parameter reference at the page  383

### ISSUE THREAD

**Issue by panjunchang** [koalaverse/hands-on-machine-learning-with-r#57]
At the page  383 the source code and the results as follows:

    h2o.getGrid(’autoencoder_grid’, sort_by = ’mse’, decreasing = FALSE)
      ## H2O Grid Details

      ## ================

      ##

     ## Grid ID: autoencoder_grid

     ## Used hyper parameters:

      ## - hidden

      ## Number of models: 5

      ## Number of failed models: 0

      ##
      ## Hyper-Parameter Search Summary: ordered by increasing mse
      ##                     hidden                 model_ids                  mse
      ## 1                    [100] autoencoder_grid3_model_2  0.00674637890553651
     ## 2          [300, 100, 300] autoencoder_grid3_model_3  0.00830502966843272
      ## 3           [100, 50, 100] autoencoder_grid3_model_4 0.011215307972822733
     ## 4                     [50] autoencoder_grid3_model_1 0.012450109189122541
      `## 5 [250, 100, 50, 100, 250] autoencoder_grid3_model_5 0.014410280145600972

I think the bestmodel id is 2 th.    But the following code referenced the 1 th.  IF it is a small mistake? Thanks!

      # Get sampled test images
      index <- sample(1:nrow(mnist$test$images), 4)
      sampled_digits <- mnist$test$images[index, ]
      colnames(sampled_digits) <- paste0(”V”, seq_len(ncol(sampled_digits)))
      # Predict reconstructed pixel values
      best_model_id <- grid_perf@model_ids[[1]]

**Comment by bradleyboehmke** [comment]
@panjunchang - you are correct, that is a typo. Thanks for catching this!  

Although `h2o.getGrid('autoencoder_grid', sort_by = 'mse', decreasing = FALSE)` returns the models in sorted order `grid_perf@model_ids[[1]]` is indexing for the first model, which is not sorted by MSE. A better way to get the `best_model_id` would be:

```r
# save sorted results
sorted_results <- h2o.getGrid('autoencoder_grid', sort_by = 'mse', decreasing = FALSE)

# S4 indexing to get best model ID
sorted_results@model_ids[[1]]
[1] "autoencoder_grid_model_2"
```
