### ISSUE TITLE
chapter 5, discussion: include a little more detail on model metrics

### ISSUE THREAD

**Issue by cunningjames** [koalaverse/hands-on-machine-learning-with-r#7]
Book version: 2019-05-25

It's been a number of chapters since the intro, and some readers are likely to need a brief refresher on ROC curves and sensitivity / specificity & friends. The PLS example doesn't really seem to come to anything for the attrition dataset, and could probably be excised to make more room.

**Comment by bgreenwell** [comment]
Seems sufficient enough to just include the reference to the corresponding metrics section.
