### ISSUE TITLE
Chapter 17. Principal Component Analysis - Section 17.5.1 Eigenvalue Criterion

### ISSUE THREAD

**Issue by ThiagoBorges81** [koalaverse/hands-on-machine-learning-with-r#74]
**date** - 2020-02-01

Please, the code chunk provided in the book is returning the error below.  

![Screenshot from 2023-10-12 17-07-32](https://github.com/koalaverse/homlr/assets/86489192/b1e68035-6b84-453b-b89c-bddeb8ab9427)  

When using "as.vector()", it output an error. I have fixed it using "as.numeric()" instead.  

This error may have been caused by a version issue. I am using:
* R version 4.3.1 (2023-06-16) -- "Beagle Scouts"  
* RStudio 2023.06.0+421 "Mountain Hydrangea" Release (583b465ecc45e60ee9de085148cd2f9741cc5214, 2023-06-06) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.06.0+421 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36  
* dplyr - 1.1.2  
* ggplot2 - 3.4.2  
* h2o - 3.42.0.2  

Thank you. I hope this is useful.

Regards

Thiago

**Comment by bgreenwell** [comment]
Thanks @ThiagoBorges81, indeed this book was written many R versions ago! We’re actively working in the second edition and will keep a more version-agnostic mind in the code examples.
