### ISSUE TITLE
chapter 6, typos

### ISSUE THREAD

**Issue by cunningjames** [koalaverse/hands-on-machine-learning-with-r#8]
- [x] Section 6.2: "The easiest way to understand regularized regression is to explain how and why [it] is applied to ordinary least squares (OLS)."

- [x] Section 6.2: "The objective in OLS regression is to find the hyperplane (e.g., a
straight line in two dimensions)" Should be "multiple dimensions", since it's not clear you only mean the specific example

- [x] Section 6.2: "Having a large number of feature[s] invites"

- [x] Section 6.2.1: "This is indicitive of ..." should be "indicative"

- [x] Section 6.5: "Variable importance for regularized models provide[s]"

**Comment by bgreenwell** [comment]
Addressed most of the typos, just not sure I'm clear about the issue with the second one?

**Comment by cunningjames** [comment]
The second one implies that the objective of OLS is to find a specifically two-dimensional hyperplane, when in principle the dimensionality of the hyperplane will depend on the number of covariates. It’s possible you’re only referring to a specific example, but I’m not sure.

**Comment by bradleyboehmke** [comment]
The example (e.g.) states "a straight line for two dimensions"...it wouldn't be a straight line in multiple dimensions.  I did add a footnote to a source about hyperplanes in case the reader wants to understand more.

**Comment by bgreenwell** [comment]
Let’s be sure the footnote/source jives with the hyperplane info in the SVM chapter. Reopened as a reminder for me to check!

**Comment by bradleyboehmke** [comment]
Good point, I didn't even think about that cross reference. I just updated the footnote so that it refers to that SVM section:

_"See Section 14.2 for more discussion on hyperplanes."_

I'll leave this open though in case you want to adjust it.

**Comment by bgreenwell** [comment]
Works for me!
