### ISSUE TITLE
chapter 6, my results for cv_glmnet differ from yours

### ISSUE THREAD

**Issue by cunningjames** [koalaverse/hands-on-machine-learning-with-r#9]
Starting in section 6.4, there are a number of places that my results don't match your code examples. This seems to stem from this code:

    # for reproducibility
    set.seed(123)

    # grid search across 
    cv_glmnet <- train(
      x = X,
      y = Y,
      method = "glmnet",
      preProc = c("zv", "center", "scale"),
      trControl = trainControl(method = "cv", number = 10),
      tuneLength = 10
    )

1. bestTune in that code snippet differs from yours (mine is 0.04688353)
2. My MSE in the comparison to previous Ames model at the end of 6.4 differs from yours:
        `> RMSE(exp(pred), exp(Y))`
        `[1] 23503.05`
3. My VIP in 6.5, figure 6.10, looks somewhat different

**Comment by bradleyboehmke** [comment]
Good catch.  This must've been caused by cacheing or something. I deleted the cached files, re-knit, and now have consistent outputs with yours.
